name: fusion
channels:
  - fastai
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - fastai=1.0.57
  - matplotlib=3.3.4
  - pandas=1.2.3
  - python<3.9
  - pytorch=1.8.1
  - torchvision=0.9.1
  - scikit-learn=0.24.1
  - pip:
      - ray[all]==1.5.1
